services:
  db:
    image: postgres:latest
    container_name: better_stack_test_db
    restart: always
    env_file:
      - .env.test
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
