// Generated by Wrangler by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
  AUTH_GITHUB_ID: string;
  AUTH_GITHUB_SECRET: string;
  BETTER_AUTH_URL: string;
  SECRET: string;
  LEMONSQUEEZY_CHECKOUT_LINK: string;
  USERS_DATABASE: D1Database;
}
